openapi: "3.0.0"
info:
  title: Fleet Management API
  version: 0.0.1
paths:
  /api/vehicles:
    get:
      operationId: operations.get_vehicles
      summary: Get list of vehicles
      responses:
        "200":
          description: "List of vehicles"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"
  /api/vehicles/{vehicle_id}/status:
    put:
      operationId: operations.update_vehicle_status
      summary: Update vehicle status
      parameters:
        - name: vehicle_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [Available, In Maintenance, Out of Service]
      responses:
        "200":
          description: "Vehicle status updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
components:
  schemas:
    Vehicle:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [Available, In Maintenance, Out of Service]
